Hello rails back end
binyamolango/hello-rails-back-end pull request #1
Opened 2024-02-14 19:23 UTC by binyamolango

#Hi Reviewer 👋
Below is a list of the accomplished tasks while working on this project:

- Created a feature branch.
- Added a workflow to the project.
- Implemented Rubocop linters.
- Generated the Greeting model.
- Ran migration file.
- Generated the API controller.
- Defined index action for API controller.
- Set up root route.
- Implemented the rack-cors dependencies.
- Fixed linters' errors.

2024-02-14 20:23 UTC, mckent05 requested changes
Hi @binyamolango, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 
- Good job implementing your rails API 👍 👍 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-02-14 20:23 UTC, mckent05 commented on README.md
> +
- You have done well so far, though I can see the link to your frontend here, but according to the project requirements you should have a link that leads directly to the frontend repo, please fix this 👍 👍

2024-02-14 20:23 UTC, mckent05 commented on config/routes.rb
> +  resources :greetings
- You have done well so far, but please note that implementing your routes this way exposes all endpoints, leaving your app prone to attacks. I suggest exposing only the index action that is in use 👍

2024-02-15 09:29 UTC, skyv26 approved these changes
## Hi @binyamolango, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## STATUS: APPROVED 🟢 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOGJmZWM5NmRjYjQ5ZjZjMjgzYTg1MzRlNDk0MDg5ZTZiM2I3YTk1NSZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/fYlennPcKut8gjKOZD/giphy.gif)

## Highlights
- Fixed the link issue in the README file ✅ 
- Update routes by adding `index` only attribute ✅ 

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-02-15 11:33 UTC, merged